config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :refunds
  root to: "refunds#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/refund.rb
class Refund < ApplicationRecord
	belongs_to :user
end

app/models/situation.rb
class Situation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :refunds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  before_action :set_refund, only: [:show, :edit, :update, :destroy]

  # GET /refunds
  # GET /refunds.json
  def index
    @refunds = Refund.all
  end

  # GET /refunds/1
  # GET /refunds/1.json
  def show
  end

  # GET /refunds/new
  def new
    @refund = Refund.new
  end

  # GET /refunds/1/edit
  def edit
  end

  # POST /refunds
  # POST /refunds.json
  def create
    @refund = Refund.new(refund_params)

    respond_to do |format|
      if @refund.save
        format.html { redirect_to @refund, notice: 'Refund was successfully created.' }
        format.json { render :show, status: :created, location: @refund }
      else
        format.html { render :new }
        format.json { render json: @refund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refunds/1
  # PATCH/PUT /refunds/1.json
  def update
    respond_to do |format|
      if @refund.update(refund_params)
        format.html { redirect_to @refund, notice: 'Refund was successfully updated.' }
        format.json { render :show, status: :ok, location: @refund }
      else
        format.html { render :edit }
        format.json { render json: @refund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refunds/1
  # DELETE /refunds/1.json
  def destroy
    @refund.destroy
    respond_to do |format|
      format.html { redirect_to refunds_url, notice: 'Refund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refund
      @refund = Refund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refund_params
      params.require(:refund).permit(:title, :value, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfCjr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/refunds/_form.html.erb
<%= form_with(model: refund, local: true) do |form| %>
  <% if refund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(refund.errors.count, "error") %> prohibited this refund from being saved:</h2>

      <ul>
      <% refund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :refund_title %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :refund_value %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :refund_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/refunds/edit.html.erb
<h1>Editing Refund</h1>

<%= render 'form', refund: @refund %>

<%= link_to 'Show', @refund %> |
<%= link_to 'Back', refunds_path %>

app/views/refunds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Refunds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @refunds.each do |refund| %>
      <tr>
        <td><%= refund.title %></td>
        <td><%= refund.value %></td>
        <td><%= refund.image %></td>
        <td><%= link_to 'Show', refund %></td>
        <td><%= link_to 'Edit', edit_refund_path(refund) %></td>
        <td><%= link_to 'Destroy', refund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refund', new_refund_path %>

app/views/refunds/new.html.erb
<h1>New Refund</h1>

<%= render 'form', refund: @refund %>

<%= link_to 'Back', refunds_path %>

app/views/refunds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @refund.title %>
</p>

<p>
  <strong>Value:</strong>
  <%= @refund.value %>
</p>

<p>
  <strong>Image:</strong>
  <%= @refund.image %>
</p>

<%= link_to 'Edit', edit_refund_path(@refund) %> |
<%= link_to 'Back', refunds_path %>